-- Postgres schema for Expense-Master (Vercel + Neon)
-- Generated by translating the existing Cloudflare D1 (SQLite) schema to Postgres.

-- =========================
-- Core SaaS / Auth
-- =========================

CREATE TABLE IF NOT EXISTS roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name TEXT NOT NULL,
  role_name_ar TEXT,
  description TEXT,
  is_system_role BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT roles_role_name_unique UNIQUE (role_name)
);

CREATE TABLE IF NOT EXISTS permissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permission_key TEXT NOT NULL,
  permission_name TEXT NOT NULL,
  permission_name_ar TEXT,
  description TEXT,
  category TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT permissions_key_unique UNIQUE (permission_key)
);

CREATE TABLE IF NOT EXISTS role_permissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  permission_id INTEGER NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT role_permissions_role_perm_unique UNIQUE (role_id, permission_id)
);

CREATE INDEX IF NOT EXISTS idx_role_permissions_role ON role_permissions(role_id);
CREATE INDEX IF NOT EXISTS idx_role_permissions_permission ON role_permissions(permission_id);
CREATE INDEX IF NOT EXISTS idx_permissions_category ON permissions(category);
CREATE INDEX IF NOT EXISTS idx_permissions_key ON permissions(permission_key);

CREATE TABLE IF NOT EXISTS packages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_name TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  duration_months INTEGER NOT NULL,
  max_calculations INTEGER,
  max_users INTEGER,
  features TEXT,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT packages_name_unique UNIQUE (package_name)
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name TEXT NOT NULL,
  package_id INTEGER NOT NULL REFERENCES packages(id),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status TEXT DEFAULT 'active',
  calculations_used INTEGER DEFAULT 0,
  tenant_id INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_tenant ON subscriptions(tenant_id);

CREATE TABLE IF NOT EXISTS subscription_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name TEXT NOT NULL,
  contact_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  package_id INTEGER NOT NULL REFERENCES packages(id),
  status TEXT DEFAULT 'pending',
  notes TEXT,
  tenant_id INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tenants (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name TEXT NOT NULL,
  slug TEXT NOT NULL,
  subdomain TEXT,
  logo_url TEXT,
  primary_color TEXT DEFAULT '#667eea',
  secondary_color TEXT DEFAULT '#764ba2',
  subscription_id INTEGER REFERENCES subscriptions(id),
  status TEXT DEFAULT 'active',
  max_users INTEGER DEFAULT 5,
  max_customers INTEGER DEFAULT 100,
  max_requests INTEGER DEFAULT 1000,
  features_json TEXT,
  settings_json TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  trial_ends_at TIMESTAMPTZ,
  subscription_ends_at TIMESTAMPTZ,
  contact_email TEXT,
  contact_phone TEXT,
  total_users INTEGER DEFAULT 0,
  total_customers INTEGER DEFAULT 0,
  total_requests INTEGER DEFAULT 0,
  CONSTRAINT tenants_company_name_unique UNIQUE (company_name),
  CONSTRAINT tenants_slug_unique UNIQUE (slug),
  CONSTRAINT tenants_subdomain_unique UNIQUE (subdomain)
);

CREATE INDEX IF NOT EXISTS idx_tenants_slug ON tenants(slug);
CREATE INDEX IF NOT EXISTS idx_tenants_subdomain ON tenants(subdomain);
CREATE INDEX IF NOT EXISTS idx_tenants_status ON tenants(status);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  role_id INTEGER DEFAULT 4 REFERENCES roles(id),
  -- legacy role string used in UI filtering
  role TEXT DEFAULT 'employee',
  user_type TEXT DEFAULT 'company',
  subscription_id INTEGER REFERENCES subscriptions(id),
  tenant_id INTEGER REFERENCES tenants(id) ON DELETE SET NULL,
  is_active INTEGER DEFAULT 1,
  last_login TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT users_username_unique UNIQUE (username),
  CONSTRAINT users_email_unique UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS idx_users_tenant ON users(tenant_id);

-- =========================
-- Banking & Rates
-- =========================

CREATE TABLE IF NOT EXISTS banks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bank_name TEXT NOT NULL,
  bank_code TEXT,
  logo_url TEXT,
  tenant_id INTEGER REFERENCES tenants(id) ON DELETE SET NULL,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT banks_name_unique UNIQUE (bank_name),
  CONSTRAINT banks_code_unique UNIQUE (bank_code)
);

CREATE INDEX IF NOT EXISTS idx_banks_tenant ON banks(tenant_id);

CREATE TABLE IF NOT EXISTS financing_types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_name TEXT NOT NULL,
  description TEXT,
  tenant_id INTEGER REFERENCES tenants(id) ON DELETE SET NULL,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT financing_types_name_unique UNIQUE (type_name)
);

CREATE INDEX IF NOT EXISTS idx_financing_types_tenant ON financing_types(tenant_id);

CREATE TABLE IF NOT EXISTS bank_financing_rates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bank_id INTEGER NOT NULL REFERENCES banks(id) ON DELETE CASCADE,
  financing_type_id INTEGER NOT NULL REFERENCES financing_types(id) ON DELETE CASCADE,
  rate NUMERIC NOT NULL,
  min_amount NUMERIC,
  max_amount NUMERIC,
  min_salary NUMERIC,
  max_salary NUMERIC,
  min_duration INTEGER,
  max_duration INTEGER,
  effective_date DATE DEFAULT CURRENT_DATE,
  tenant_id INTEGER REFERENCES tenants(id) ON DELETE SET NULL,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rates_tenant ON bank_financing_rates(tenant_id);

-- =========================
-- Customers & Requests
-- =========================

CREATE TABLE IF NOT EXISTS customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  national_id TEXT,
  birthdate DATE,
  work_start_date DATE,
  city TEXT,
  employer_name TEXT,
  job_title TEXT,
  monthly_salary NUMERIC,
  -- assignment / multi-tenant
  tenant_id INTEGER NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  assigned_to INTEGER REFERENCES users(id) ON DELETE SET NULL,
  -- calculator fields
  financing_amount NUMERIC DEFAULT 0,
  monthly_obligations NUMERIC DEFAULT 0,
  financing_type_id INTEGER REFERENCES financing_types(id) ON DELETE SET NULL,
  financing_duration_months INTEGER,
  best_bank_id INTEGER REFERENCES banks(id) ON DELETE SET NULL,
  best_rate NUMERIC,
  monthly_payment NUMERIC,
  total_payment NUMERIC,
  calculation_date TIMESTAMPTZ,
  first_calculation_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_customers_tenant ON customers(tenant_id);
CREATE INDEX IF NOT EXISTS idx_customers_assigned_to ON customers(assigned_to);
CREATE INDEX IF NOT EXISTS idx_customers_financing_type ON customers(financing_type_id);
CREATE INDEX IF NOT EXISTS idx_customers_best_bank ON customers(best_bank_id);
CREATE INDEX IF NOT EXISTS idx_customers_calculation_date ON customers(calculation_date);

CREATE TABLE IF NOT EXISTS financing_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  financing_type_id INTEGER DEFAULT 1 REFERENCES financing_types(id) ON DELETE SET NULL,
  requested_amount NUMERIC NOT NULL,
  duration_months INTEGER,
  salary_at_request NUMERIC,
  selected_bank_id INTEGER REFERENCES banks(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'pending',
  notes TEXT,
  tenant_id INTEGER NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  -- workflow & status timestamps
  current_stage_id INTEGER,
  stage_entered_at TIMESTAMPTZ,
  approved_at TIMESTAMPTZ,
  rejected_at TIMESTAMPTZ,
  reviewed_at TIMESTAMPTZ,
  pending_at TIMESTAMPTZ DEFAULT NOW(),
  under_review_at TIMESTAMPTZ,
  processing_at TIMESTAMPTZ,
  -- attachment urls (kept for compatibility with existing UI)
  monthly_obligations NUMERIC DEFAULT 0,
  monthly_payment NUMERIC,
  id_attachment_url TEXT,
  bank_statement_attachment_url TEXT,
  salary_attachment_url TEXT,
  additional_attachment_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_requests_tenant ON financing_requests(tenant_id);
CREATE INDEX IF NOT EXISTS idx_requests_customer ON financing_requests(customer_id);
CREATE INDEX IF NOT EXISTS idx_financing_requests_status_timestamps
  ON financing_requests(pending_at, under_review_at, processing_at, approved_at, rejected_at);

CREATE TABLE IF NOT EXISTS financing_request_status_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id INTEGER NOT NULL REFERENCES financing_requests(id) ON DELETE CASCADE,
  old_status TEXT,
  new_status TEXT NOT NULL,
  changed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_status_history_request ON financing_request_status_history(request_id);
CREATE INDEX IF NOT EXISTS idx_status_history_status ON financing_request_status_history(new_status);
CREATE INDEX IF NOT EXISTS idx_status_history_date ON financing_request_status_history(created_at);

-- =========================
-- Assignments
-- =========================

CREATE TABLE IF NOT EXISTS customer_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  employee_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  assigned_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  assigned_at TIMESTAMPTZ DEFAULT NOW(),
  notes TEXT,
  CONSTRAINT customer_assignments_customer_unique UNIQUE (customer_id)
);

CREATE INDEX IF NOT EXISTS idx_assignments_customer ON customer_assignments(customer_id);
CREATE INDEX IF NOT EXISTS idx_assignments_employee ON customer_assignments(employee_id);
CREATE INDEX IF NOT EXISTS idx_assignments_date ON customer_assignments(assigned_at);

CREATE TABLE IF NOT EXISTS assignment_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  old_employee_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  new_employee_id INTEGER NOT NULL REFERENCES users(id) ON DELETE SET NULL,
  changed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  changed_at TIMESTAMPTZ DEFAULT NOW(),
  notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_assignment_history_customer ON assignment_history(customer_id);
CREATE INDEX IF NOT EXISTS idx_assignment_history_employee ON assignment_history(new_employee_id);

-- =========================
-- Notifications
-- =========================

CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  tenant_id INTEGER REFERENCES tenants(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'info',
  category TEXT DEFAULT 'general',
  related_request_id INTEGER REFERENCES financing_requests(id) ON DELETE CASCADE,
  is_read INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  read_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_request ON notifications(related_request_id);
CREATE INDEX IF NOT EXISTS idx_notifications_tenant ON notifications(tenant_id);

-- =========================
-- Workflow
-- =========================

CREATE TABLE IF NOT EXISTS workflow_stages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stage_name TEXT NOT NULL,
  stage_name_ar TEXT NOT NULL,
  stage_order INTEGER NOT NULL,
  stage_color TEXT DEFAULT '#3B82F6',
  stage_icon TEXT DEFAULT 'fa-circle',
  description TEXT,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT workflow_stages_name_unique UNIQUE(stage_name)
);

CREATE TABLE IF NOT EXISTS workflow_stage_transitions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id INTEGER NOT NULL REFERENCES financing_requests(id) ON DELETE CASCADE,
  from_stage_id INTEGER REFERENCES workflow_stages(id) ON DELETE SET NULL,
  to_stage_id INTEGER NOT NULL REFERENCES workflow_stages(id),
  transitioned_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  notes TEXT,
  duration_minutes INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS workflow_stage_actions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id INTEGER NOT NULL REFERENCES financing_requests(id) ON DELETE CASCADE,
  stage_id INTEGER NOT NULL REFERENCES workflow_stages(id),
  action_type TEXT NOT NULL,
  action_data TEXT,
  performed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS workflow_stage_tasks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id INTEGER NOT NULL REFERENCES financing_requests(id) ON DELETE CASCADE,
  stage_id INTEGER NOT NULL REFERENCES workflow_stages(id),
  task_title TEXT NOT NULL,
  task_description TEXT,
  assigned_to INTEGER REFERENCES users(id) ON DELETE SET NULL,
  due_date TIMESTAMPTZ,
  status TEXT DEFAULT 'pending',
  completed_at TIMESTAMPTZ,
  completed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  priority TEXT DEFAULT 'medium',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_transitions_request ON workflow_stage_transitions(request_id);
CREATE INDEX IF NOT EXISTS idx_transitions_stage ON workflow_stage_transitions(to_stage_id);
CREATE INDEX IF NOT EXISTS idx_actions_request ON workflow_stage_actions(request_id);
CREATE INDEX IF NOT EXISTS idx_tasks_request ON workflow_stage_tasks(request_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned ON workflow_stage_tasks(assigned_to);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON workflow_stage_tasks(status);

-- =========================
-- Payments
-- =========================

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  financing_request_id INTEGER NOT NULL REFERENCES financing_requests(id) ON DELETE CASCADE,
  customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  tenant_id INTEGER NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  employee_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  amount NUMERIC NOT NULL,
  payment_date DATE NOT NULL,
  payment_method TEXT DEFAULT 'cash',
  receipt_number TEXT,
  notes TEXT,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payments_tenant ON payments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_payments_request ON payments(financing_request_id);
CREATE INDEX IF NOT EXISTS idx_payments_customer ON payments(customer_id);
CREATE INDEX IF NOT EXISTS idx_payments_employee ON payments(employee_id);
CREATE INDEX IF NOT EXISTS idx_payments_date ON payments(payment_date);

-- =========================
-- Calculator logging (optional)
-- =========================

CREATE TABLE IF NOT EXISTS calculations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  subscription_id INTEGER REFERENCES subscriptions(id) ON DELETE SET NULL,
  financing_type_id INTEGER REFERENCES financing_types(id) ON DELETE SET NULL,
  bank_id INTEGER REFERENCES banks(id) ON DELETE SET NULL,
  amount NUMERIC NOT NULL,
  duration_months INTEGER,
  salary NUMERIC,
  rate NUMERIC,
  monthly_payment NUMERIC,
  total_payment NUMERIC,
  total_interest NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS conversions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_ip TEXT,
  page_url TEXT,
  conversion_type TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================
-- Password reset / verification
-- =========================

CREATE TABLE IF NOT EXISTS password_change_notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- legacy fields (if used)
  old_password_hash TEXT,
  new_password_hash TEXT,
  changed_at TIMESTAMPTZ,
  -- current forgot-password flow fields (used by src/index.tsx)
  verification_code TEXT,
  expires_at TIMESTAMPTZ,
  is_used INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================
-- Attachments mapping (Vercel Blob)
-- =========================

CREATE TABLE IF NOT EXISTS attachments (
  path TEXT PRIMARY KEY,
  blob_url TEXT NOT NULL,
  content_type TEXT,
  size_bytes BIGINT,
  request_id INTEGER REFERENCES financing_requests(id) ON DELETE CASCADE,
  attachment_type TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_attachments_request ON attachments(request_id);


